### PR TITLE
Update casacore to 3.1.1 and make less version needy

### PR DESCRIPTION
**Pull request by gijzelaerr**
unfortunately this still can't find the new boost python.

a minimal `CMakeLists.txt` like:
```
cmake_minimum_required(VERSION 3.13)
find_package(Boost REQUIRED COMPONENTS python)
```
still gives:
```
$  cmake ..
CMake Error at /usr/local/Cellar/cmake/3.13.1/share/cmake/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.68.0

  Boost include path: /usr/local/include

  Could not find the following Boost libraries:

          boost_python

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:2 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/gijs/bla/build/CMakeFiles/CMakeOutput.log".
```

with `cmake 3.13.1` and boost `1.68.0` while it looks like this bug has been fixed since `cmake 3.11.0`

https://gitlab.kitware.com/cmake/cmake/commit/1673923c303c6a4184904c4c5849911feddb87e7

### CODE REVIEW

**Comment by gijzelaerr** [comment]
bingo!

https://cmake.org/cmake/help/v3.13/module/FindBoost.html

```
Note that Boost Python components require a Python version suffix (Boost 1.67 and later), e.g. python36 or python27 for the versions built against Python 3.6 and 2.7, respectively. This also applies to additional components using Python including mpi_python and numpy. Earlier Boost releases may use distribution-specific suffixes such as 2, 3 or 2.7. These may also be used as suffixes, but note that they are not portable.
```

**Comment by gijzelaerr** [comment]
i've issued a PR with a fix upstream https://github.com/casacore/casacore/pull/846

**Comment by gijzelaerr** [comment]
we also need to make sure `PYTHON2_LIBRARIES` is correctly set, since by default something goes wrong:
```
-- PYTHON2_EXECUTABLE ......... = /usr/local/bin/python2
-- PYTHON2_LIBRARIES........... = /usr/lib/libpython2.7.dylib
-- PYTHON2_NUMPY_INCLUDE_DIRS . = /usr/local/lib/python2.7/site-packages/numpy/core/include
-- PYTHON2_Boost_LIBRARIES .... = /usr/local/lib/libboost_python27-mt.dylib
-- PYTHON2_Boost_INCLUDE_DIRS . = /usr/local/include
-- PYTHON3_EXECUTABLE ......... = /usr/local/bin/python3.7
-- PYTHON3_LIBRARIES .......... = /usr/local/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib
-- PYTHON3_NUMPY_INCLUDE_DIRS . = /usr/local/lib/python3.7/site-packages/numpy/core/include
-- PYTHON3_Boost_LIBRARIES .... = /usr/local/lib/libboost_python37-mt.dylib
-- PYTHON3_Boost_INCLUDE_DIRS . = /usr/local/include
```

**Comment by gijzelaerr** [comment]
ah you already do that. @ludwigschwardt you are my hero.

**Comment by ludwigschwardt** [comment]
I aim to please!

**Comment by ludwigschwardt** [comment]
Anything more here? What about `PYTHON2_LIBRARIES`?

I guess it's picking up the system Python (associated with the default command `python`) instead of the brew-provided `python2`.

**Comment by gijzelaerr** [comment]
yes, we need to make sure that is overwritten in the recipe

**Comment by ludwigschwardt** [comment]
I'm busy extending this branch to catch up with the latest changes...

**Comment by ludwigschwardt** [comment]
This currently does v3.1.0 fine but I suspect HEAD is broken. Should we merge this so long and open another PR once 3.1.1 comes out? That would probably allow me to get rid of the patches in that PR.

**Comment by ludwigschwardt** [comment]
The HEAD support now works again (based off casacore/casacore#922).

**Comment by ludwigschwardt** [comment]
@gijzelaerr, if we can get casacore/casacore#922 merged in time for the 3.1.1 release, I can remove all the patches in this formula... 😉

**Comment by ludwigschwardt** [comment]
This works on my laptop with no patches now... Happy to merge if you are.

**Pull request merged**
